name = "UniDimentionTDSE"
uuid = "22cf1bb6-fd48-446e-9a06-38831a1521c4"
authors = ["KMarmorat <kenzo.marmorat@ens.psl.eu> and contributors"]
version = "1.0.0-DEV"

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
